### ISSUE TITLE
add https redirection

### ISSUE THREAD

**Issue by h0wardch3ng** [4679/nginx-proxy-docker#1]
http to https

**Comment by 4679** [comment]
nginx配置我抄的 有时间研究下

**Comment by yangg** [comment]
直接取 $scheme 就行了
```conf
# create a proxy
location ~ ^/p/(?<hostx>[^/]+)/(?<pathx>.+)$ {
    resolver 8.8.8.8;
    proxy_redirect off;
    proxy_pass $scheme://$hostx/$pathx;
    proxy_set_header referer $scheme://$hostx;
    proxy_set_header Accept-encoding '';
}
```

**Comment by h0wardch3ng** [comment]
> 直接取 $scheme 就行了
> 
> ``` conf
> # create a proxy
> location ~ ^/p/(?<hostx>[^/]+)/(?<pathx>.+)$ {
>     resolver 8.8.8.8;
>     proxy_redirect off;
>     proxy_pass $scheme://$hostx/$pathx;
>     proxy_set_header referer $scheme://$hostx;
>     proxy_set_header Accept-encoding '';
> }
> ```
> 

thx
